### ISSUE TITLE
Refactor meetup requirement into the gitevents-meetup package

### ISSUE THREAD

**Issue by joemckie** [GitEvents/gitevents-webhook#12]
If multiple services are to be developed using GitEvents, this package should be platform indifferent. I'd suggest to move [the following](https://github.com/GitEvents/gitevents-webhook/blob/master/index.js#L23) into the `gitevents-meetup` package.

**Comment by PatrickHeneise** [comment]
Sorry, this is a mistake. It's supposed to say `config.github`, not meetup.
