### ISSUE TITLE
dupe

### ISSUE THREAD

**Issue by iancrowther** [GitEvents/gitevents-webhook#3]
anyone seen this before?

https://github.com/rvagg/github-webhook-handler

**Comment by h02e56** [comment]
nope,
know rvagg for through2  that i’ve used before

## Josep Boada

E-mail:     josep@h02e56.com
Phone:  +34 627944197
Skype:  h02e56

**Comment by ifraixedes** [comment]
Wop, definitely we have to take a look.
@iancrowther good spot

**Comment by iancrowther** [comment]
this will be solid as a rock if I know rodd..

**Comment by ifraixedes** [comment]
Yes, we can rely on it.

**Comment by PatrickHeneise** [comment]
Damn, I wrote a new implementation. Can anyone refactor with github-webhook-handler?

**Comment by h02e56** [comment]
hi 
I have been taking a look and refreshing all about this.
we could put github-web-handler on  root/main file, receive payload there and send it to current giteevents-webwook module(cleaning auth)  to manage data or put it on current lib/handler to do the same and keep current structure,  what do u think?

**Comment by PatrickHeneise** [comment]
Yes, that's how it's done right now anyway, except that I wrote the auth/verification stuff myself and not as well as github-webhook-handler.

**Comment by h02e56** [comment]
check if this is a good way https://github.com/h02e56/gitevents/tree/weebhook-handler
need refactor tests i will try

**Comment by PatrickHeneise** [comment]
That looks good!
